### PR TITLE
fix: ensure settings styles are aligned with tools

### LINKED ISSUE #446: UI consistency bugs between settings and tools
https://github.com/user-attachments/assets/5c0d9547-75b6-4a3a-8cda-e7d83eb878c4

- [ ] item font size and weight
- [ ] flexbox gaps
- [ ] padding

### PR DESCRIPTION
**Pull request by datasalaryman**
## Description

We use the standard components used in Tools for the settings menu items

Closes #446 

## Screenshots / Video

https://github.com/user-attachments/assets/80b1ce65-488e-4209-9a9c-0a156452fc89

### CODE REVIEW

**Comment by datasalaryman** [comment]
done @beeman, should be closer to the structure in the component now

File: packages/settings/src/ui/settings-ui-page-item.tsx [hunk 1]
```diff
@@ -1,24 +1,22 @@
...
-            'text-muted-foreground': !isActive,
-          })
-        }
-        to={`/settings/${page.id}`}
-      >
-        <SettingsUiPageHeader page={page} />
-        <UiIcon icon="chevronRight" />
-      </NavLink>
-    </div>
+    <Item asChild key={page.id} size="sm" variant="outline">
```
Comment (beeman) [inline packages/settings/src/ui/settings-ui-page-item.tsx]: We want to use the `NavLink` component to make sure we highlight the active component:

```tsx
export function SettingsUiPageItem({ page }: { page: SettingsPage }) {
  return (
    <NavLink to={`/settings/${page.id}`}>
      {({ isActive }) => (
        <Item size="sm" variant={isActive ? 'muted' : 'outline'}>
          <ItemMedia>
            <UiIcon icon={page.icon} />
          </ItemMedia>
          <ItemContent>
            <ItemTitle className="text-xl">{page.name}</ItemTitle>
          </ItemContent>
          <ItemActions>
            <UiIcon className="size-4" icon="chevronRight" />
          </ItemActions>
        </Item>
      )}
    </NavLink>
  )
}
```
