### PR TITLE
fix(portfolio): transaction group header time

### LINKED ISSUE #474: Incorrect time `4 hours ago` after requesting an airdrop 5 seconds prior
**Describe the bug**
Incorrect time `4 hours ago` after requesting an airdrop 5 seconds prior.

**To Reproduce**

1. Create a new wallet
2. Request an airdrop
3. Go to activity tab

**Expected behavior**
It should not shown `4 hours ago` and probably shown `now` or `x seconds ago`

**Screenshots**
Image

### PR DESCRIPTION
**Pull request by Nitinyadav237**
fix #474 

## Description
Fixed transaction group headers showing "Incorrect time 4 hours ago" instead of day indicators like "Today"/"Yesterday".

**Changes:**
- Replaced `UiTime` with `UiRelativeDate` using `date-fns`
- Group headers now show: "Today", "Yesterday", day name

Closes #474

## Screenshots / Video
image

### CODE REVIEW

File: packages/portfolio/src/ui/group-activity-items.tsx [hunk 1]
```diff
@@ -18,7 +18,7 @@ export function groupActivityItems(txs: GetActivityItems): { date: Date; transac
   }, new Map<string, GetActivityItem[]>())
 
   return Array.from(grouped.entries()).map(([dateKey, transactions]) => ({
-    date: new Date(dateKey),
+    date: unixTimestampToDate(transactions[0]?.blockTime ?? null) ?? new Date(dateKey),
```
Comment (beeman) [inline packages/portfolio/src/ui/group-activity-items.tsx]: Why do you take the time of the first tx here? It should be the time of the group entry?

**Review by beeman — APPROVED** [review]
