### PR TITLE
fix(settings): network deletion crash

### LINKED ISSUE #618: Crash when deleting currently active network
## Describe the bug

App crashes when deleting the currently active network from settings.

## To Reproduce

1. Switch to any network (e.g., "Devnet", "Testnet", or a custom network)
2. Go to 'Settings' → 'Networks'
3. Delete the currently active network
4. App crashes

## Expected behavior

wallet should automatically switch to another network before deletion and continue working normally.

### Root Cause

The code deleted the network but didn't update `activeNetworkId`, causing the UI to reference a non-existent network.

Image

### PR DESCRIPTION
**Pull request by Nitinyadav237**
fix #618 

----

> [!IMPORTANT]
> Prevents deletion of active network in `networkDelete()` and updates error message in `SettingsFeatureNetworkList`.
> 
>   - **Behavior**:
>     - Prevents deletion of active network in `networkDelete()` in `network-delete.ts` by checking `activeNetworkId`.
>     - Updates error message in `SettingsFeatureNetworkList` to inform user they cannot delete active network.
>   - **Tests**:
>     - Adds test in `network-delete.test.ts` to verify active network cannot be deleted.
>     - Clears `db.settings` in `beforeEach` to ensure clean test state.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=samui-build%2Fsamui-wallet&utm_source=github&utm_medium=referral)<sup> for ba57454ceb7bebf7f36ba874a10c969b7ff2f602. You can [customize](https://app.ellipsis.dev/samui-build/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Review by beeman — COMMENTED** [review]
It's good to make this inactive in the ui, but we should also have this in the db layer.

I think the `networkDelete` function should be updated like so, and we should have a test that tests this case to make sure it works as expected and that we don't introduce regressions.

```ts
export async function networkDelete(db: Database, id: string): Promise<void> {
  return db.transaction('rw', db.networks, db.settings, async () => {
    const activeNetworkId = await settingGetValue(db, 'activeNetworkId')
    if (id === activeNetworkId) {
      throw new Error('Cannot delete active network')
    }
    const { data, error } = await tryCatch(db.networks.delete(id))
    if (error) {
      console.log(error)
      throw new Error(`Error deleting network with id ${id}`)
    }
    return data
  })
}
```

File: packages/settings/src/ui/settings-ui-network-list.tsx [hunk 1]
```diff
@@ -43,7 +44,7 @@ export function SettingsUiNetworkList({
               description="This action cannot be reversed."
               title="Are you sure you want to delete this network?"
             >
-              <Button size="icon" title={t(($) => $.actionDelete)} variant="outline">
+              <Button disabled={isLastNetwork} size="icon" title={t(($) => $.actionDelete)} variant="outline">
```
Comment (beeman) [inline packages/settings/src/ui/settings-ui-network-list.tsx]: I think the best way to go about this is to disable the active network. Combined with the logic in the db layer this seems like the easiest way to go about it.

**Comment by tobeycodes** [comment]
> It's debatable what's the 'best' solution, and not convinced we should aim for that to fix this bug.
> 
> I don't see any useful way in supporting a wallet without any networks configured. So maybe we should update it so that after the last one gets deleted we re-populate the initial ones.

That's sort of my point. By disabling the delete button we are not fixing the bug, we are hiding the bug by a UI change. The bug still exists. 

I don't think we need to support a wallet without any networks configured but we should encourage them to add a network if they removed them all. I do not think we should re-populate the initial ones after the last one gets deleted as that feels like a side effect to me. In my opinion this generally adds code complexity and a confusing UX for the end user. If they delete something, the end result should only ever be a deletion.

File: packages/settings/src/settings-feature-network-list.tsx [hunk 2]
```diff
@@ -14,7 +14,7 @@ export function SettingsFeatureNetworkList() {
   const { t } = useTranslation('settings')
   const page = useSettingsPage({ pageId: 'networks' })
   const deleteMutation = useNetworkDelete({
-    onError: () => toastError('Error deleting network'),
+    onError: () => toastError('You cannot delete the active network. Please change networks and try again'),
```
Comment (tobeycodes) [inline packages/settings/src/settings-feature-network-list.tsx]: **question:** can we use the error thrown in `networkDelete` here. So something like `onError: (error) => toastError(error.message)` and move the error message to the `networkDelete`

```
onError: (err: TError, variables: TVariables, onMutateResult: TOnMutateResult | undefined, context: MutationFunctionContext) => Promise<unknown> | unknown
```

File: packages/db/test/network-delete.test.ts [hunk 3]
```diff
@@ -28,6 +29,26 @@ describe('network-delete', () => {
...
       expect(deletedItem).toBeNull()
     })
+    it('should not delete an active network', async () => {
+      // ARRANGE
+      expect.assertions(1)
+      const input = testNetworkCreateInput()
+      const id = await networkCreate(db, input)
+      const [key, value] = testSettingSetInput(id)
+
+      await db.settings.put({
```
Comment (beeman) [inline packages/db/test/network-delete.test.ts]: Let's use `await settingSetValue(db, key, value)` to set this.

**Review by beeman — APPROVED** [review]
Thanks a lot @Nitinyadav237 👍
